### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by acolombier** [ArianK16a/android_device_fairphone_FP6#7]
I thought I would create a meta issue to start listing issues I have found, we can then create dedicated issue in case these requires deep-dive or investigation  - happy to go with another approach if you would want to do something different!

## Top priority / MVP

- [x] USB tethering leads to system crash #35 
- [x] SystemUI crashes once on boot #37 
<details>
  <summary>lineage-22.2</summary>

- [x] Double tap to wake doesn't work #16
- [x] Camera can only do 30 fps
- [x] RIL #12
- [x] SELinux #8 
- [x] e-SIM management #25 
- [x] Mobile data is not working #27 
</details>

## Low Priority / Nice to have

- [ ] Alert slider app triggers too often
<details>
  <summary>lineage-22.2</summary>

- [x] Fairphone "Moment" button doesn't do anything #9
- [x] Plugging phone when off doesn't show the battery charging screen
- [x] Status bar info get cut by the rounder corners or the camera
- [x] Some screen animation feels broken, perhaps something with graphic driver? (potentially due to debug build)
- [x] Heating issue (could be linked with #6)
</details>

## Unmerged platform side change
linege-23.0 builds without repoicks! 🥳 
<details>
  <summary>lineage-22.2</summary>
  
- https://review.lineageos.org/c/LineageOS/android_vendor_qcom_opensource_display-commonsys-intf/+/443078
- - Might not be merged due to low interest for testing other devices on lineage-22.2 currently, but this is already applied on lineage-23
- https://review.lineageos.org/c/LineageOS/android_vendor_qcom_opensource_vibrator/+/443063
- - We will adjust the vibrator driver to work without this #13
- https://review.lineageos.org/c/LineageOS/android_device_qcom_sepolicy_vndr/+/443059
- - We will adjust the sepolicy to work without this
</details>

## Build instructions
https://github.com/ArianK16a/android_device_fairphone_FP6/wiki/Build-instructions

**Comment by ArianK16a** [comment]
Camera being only able to do 30fps seems to be related to media profiles configs, probably the right ones are not picked up. Check the init.qti.media scripts (currently in proprietary-files.txt)
https://github.com/ArianK16a/android_device_fairphone_FP6/commit/e0f453737fb13905534e7fe1abf4c546b6693686 was a lazy fix, the "proper" one is this: https://github.com/LineageOS/android_device_xiaomi_sm8450-common/commit/431ecb8674e620f164a9f26753a34a05e9c56ab0

Possibly the property can not even be set from system.prop, i can't check it right now but that would explain the wrong fps being picked up. Oh and i also noticed screen recordings can't be saved, this should also be media profiles related.

**Comment by ArianK16a** [comment]
Regarding double tap to wake, we need to specify the path to the sysfs node to enable it. https://github.com/ArianK16a/android_kernel_fairphone_sm7635-modules/blob/lineage-22.2/qcom/opensource/touch-drivers/eswin_touch/eswin_eph861x.c#L1774 this declares the node, i don't know the exact path but you can find it easily with `find /sys -name gesture_wakeup` and then specfiy it (`TARGET_TAP_TO_WAKE_NODE` in BoardConfig.mk)

**Comment by ArianK16a** [comment]
I'd give a low priority to the fairphone moments switch, but we might be able to take some inspiration from the oneplus alert slider handling: https://github.com/LineageOS/android_hardware_oplus/tree/lineage-22.2/KeyHandler

**Comment by ArianK16a** [comment]
Offline charging being broken surprises me, i did see the screen on FP6 before once :D
No idea what's up with that as of now, but i'd say that's a low priority too for now :)

**Comment by ArianK16a** [comment]
Regarding screen animations, are you still building eng builds? They usually perform much worse due to a lot of unnecessary debugging being enabled.
I think we are in a good enough state to switch to userdebug builds, we should not have many issues with booting anymore and then we can enable rooted adb debugging in developer options.
We should also add the QTI perf stack back in order for some boosting to work. I removed it due to immense logspam for now, but this should rather be fixed :)

**Comment by acolombier** [comment]
Thank you for all this feedback! I have adjusted the initial post to highlight priority.

**Comment by acolombier** [comment]
Added `e-SIM management` in the MVP list as it will be required to use the phone. I reckon this is mostly config on LOS to make it work? Happy to get that setup if you can give me a pointer :)

**Comment by ArianK16a** [comment]
> Added `e-SIM management` in the MVP list as it will be required to use the phone. I reckon this is mostly config on LOS to make it work? Happy to get that setup if you can give me a pointer :)

This sounds reasonable. I unfortunately don't have an esim to test it. I think in theory https://review.lineageos.org/c/LineageOS/android_device_shift_axolotl/+/417749 should be sufficient.
Ideally we would ditch the proprietary EuiccGoogle app and replace it with https://gitea.angry.im/PeterCxy/OpenEUICC - but this might need a little bit more work. For now we can go with the google app.

**Comment by acolombier** [comment]
Thanks I'll have a look!

Also, I feel like the screen shape is not ideally configured, with some notification icons or the clock sometime being cut by the camera hole, the screen rounded corner. Same here, if you have any pointers, I can try to look at this - adding a "Nice to have" for now since it isn't critical!

**Comment by ArianK16a** [comment]
> Thanks I'll have a look!
> 
> Also, I feel like the screen shape is not ideally configured, with some notification icons or the clock sometime being cut by the camera hole, the screen rounded corner. Same here, if you have any pointers, I can try to look at this - adding a "Nice to have" for now since it isn't critical!

I have fixed this today (i think, feel free to comment if it doesn't seem fine to you).
i have also added a section with currently required repopicks

**Comment by acolombier** [comment]
I was not able to boot on the latest head (not even reach boot anim!). Looked like there was some SEPolicy missing for Zygote to boot:

```patch
diff --git a/sepolicy/vendor/genfs_contexts b/sepolicy/vendor/genfs_contexts
index 7f313a9..444f444 100644
--- a/sepolicy/vendor/genfs_contexts
+++ b/sepolicy/vendor/genfs_contexts
@@ -5,6 +5,7 @@ genfscon sysfs /emkit/info                           u:object_r:vendor_sysfs_inf
 genfscon sysfs /bus/spi/drivers/eswin_eph861x  u:object_r:fp_mmitest_sysfs:s0
 genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a80000.spi/spi_master/spi0/spi0.0                     u:object_r:fp_mmitest_sysfs:s0
 genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a80000.spi/spi_master/spi0/spi0.0/wakeup  u:object_r:sysfs_wakeup:s0
+genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a84000.i2c/i2c-1/1-0027/wakeup  u:object_r:sysfs_wakeup:s0
 
 # Vibrator
 genfscon sysfs /devices/platform/soc/8c0000.qcom,qupv3_1_geni_se/880000.i2c/i2c-7/7-005a/leds/aw_vibrator         u:object_r:sysfs_leds:s0
```

Also, did some spot checks with SELinux and everything appears to be working, including the stock camera (beside the slowmo camera, that is still not correctly exposed by the vendor QTI as per `dumpsys media.camera`)! Nice one 🚀 

Good new is the charging boot is also now working! :D

I'm just testing Google EUICC now and will get a PR up if this works, before I get to try and setup OpenEUICC.

My last need will be to be able to relock the booloader (not sure if you have any experience with that?), and then I can start daily driving it 😍

**Comment by ArianK16a** [comment]
> I was not able to boot on the latest head (not even reach boot anim!). Looked like there was some SEPolicy missing for Zygote to boot:
> 
> ```patch
> diff --git a/sepolicy/vendor/genfs_contexts b/sepolicy/vendor/genfs_contexts
> index 7f313a9..444f444 100644
> --- a/sepolicy/vendor/genfs_contexts
> +++ b/sepolicy/vendor/genfs_contexts
> @@ -5,6 +5,7 @@ genfscon sysfs /emkit/info                           u:object_r:vendor_sysfs_inf
>  genfscon sysfs /bus/spi/drivers/eswin_eph861x  u:object_r:fp_mmitest_sysfs:s0
>  genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a80000.spi/spi_master/spi0/spi0.0                     u:object_r:fp_mmitest_sysfs:s0
>  genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a80000.spi/spi_master/spi0/spi0.0/wakeup  u:object_r:sysfs_wakeup:s0
> +genfscon sysfs /devices/platform/soc/ac0000.qcom,qupv3_0_geni_se/a84000.i2c/i2c-1/1-0027/wakeup  u:object_r:sysfs_wakeup:s0
>  
>  # Vibrator
>  genfscon sysfs /devices/platform/soc/8c0000.qcom,qupv3_1_geni_se/880000.i2c/i2c-7/7-005a/leds/aw_vibrator         u:object_r:sysfs_leds:s0
> ```
> 
> Also, did some spot checks with SELinux and everything appears to be working, including the stock camera (beside the slowmo camera, that is still not correctly exposed by the vendor QTI as per `dumpsys media.camera`)! Nice one 🚀 
> 
> Good new is the charging boot is also now working! :D
> 
> I'm just testing Google EUICC now and will get a PR up if this works, before I get to try and setup OpenEUICC.
> 
> My last need will be to be able to relock the booloader (not sure if you have any experience with that?), and then I can start daily driving it 😍 

Hmm, sysfs_wakeup labels should never prevent boot afaik - are you sure that it wasn't the display change that was missing on the build and it was coincidence with the sepolicy label? 😅
I don't have any experience with relocking the bootloader yet, but I'm sure we can figure that out :)

**Comment by acolombier** [comment]
> are you sure that it wasn't the display change that was missing on the build and it was coincidence with the sepolicy label? 😅

Unfortunately, I did not keep the traceback with me, but Zygote backtrace was explicitly calling out of this file not being readable due to SEPolicy. Worth to say I had done a fresh `repo sync` and used the latest FP OTA zip file, maybe it explains why?

> I don't have any experience with relocking the bootloader yet, but I'm sure we can figure that out :)

Amazing! Definitely the last step of the todo list, but definitely looking forward to close that one :)

**Comment by acolombier** [comment]
> I'm just testing Google EUICC now and will get a PR up if this works, before I get to try and setup OpenEUICC.

Sadly, no lock so far, I am getting this backtrace:
```
AndroidRuntime: FATAL EXCEPTION: EuiccService #1
AndroidRuntime: Process: com.qualcomm.qti.lpa, PID: 3445
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/extphone/Token;
AndroidRuntime: 	at com.qualcomm.qti.lpa.QtiEuiccServiceImpl.getNextToken(QtiEuiccServiceImpl.java:409)
AndroidRuntime: 	at com.qualcomm.qti.lpa.QtiEuiccServiceImpl.onGetEuiccProfileInfoList(QtiEuiccServiceImpl.java:185)
AndroidRuntime: 	at android.service.euicc.EuiccService$IEuiccServiceWrapper$7.run(EuiccService.java:986)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1119)
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qti.extphone.Token
AndroidRuntime: 	... 6 more
```

Not clear what's wrong, it feels like somehow [extphone](https://github.com/LineageOS/android_hardware_lineage_telephony) is missing, though it is in the device.mk?

**Comment by acolombier** [comment]
> I'm just testing Google EUICC now and will get a PR up

 PR ready for review: #25

**Comment by AnonAlly** [comment]
Hi.

Thanks for this ROM 😛👍.

Just one question: with this package, do we have MicroG or is it Play services ?

Thanks in advance

**Comment by ArianK16a** [comment]
I've updated this for lineage-23.0

**Comment by acolombier** [comment]
Great! I hadn't had much time to help you lately, but I will free up some time in the coming weeks! Now that I am daily driving my FP6 on LOS, I also have the issue on how can I safely develop on it without messing up that data... 😅 (In case you have any tip :) )

I also would like to give it a go on how to get it to pass play integrity, but also keen not to add Magisk and related and keep the phone with a "LOS stock experience" (+setup, like for the vendor camera).
Obviously, I know this won't be in the official LOS build as it goes [against the project stance](https://lineageos.org/PlayIntegrity/), but same here, if you have some tips to share, I would be very keen to explore it, so I can at least document how one could get an FP6 with LOS and usable Android system :D

**Comment by rutgerputter** [comment]
> I've updated this for lineage-23.0

Updated this morning and it works great. Is it me, or are the haptics much improved?

**Comment by ArianK16a** [comment]
> > I've updated this for lineage-23.0
> 
> Updated this morning and it works great. Is it me, or are the haptics much improved?

Yes they are different now since we dropped the Fairphone changes to the vibrator hal. Seems like their "improvements" aren't that nice after all.

**Comment by acolombier** [comment]
> Updated this morning and it works great. Is it me, or are the haptics much improved?

Were you able to simply apply the update as an OTA or did you need to format your data partition?

**Comment by rutgerputter** [comment]
> > Updated this morning and it works great. Is it me, or are the haptics much improved?
> 
> Were you able to simply apply the update as an OTA or did you need to format your data partition?

I couldn't update using the updater app, so I rebooted into recovery and `adb sideloaded` the zip file. No wipe needed.

I had one force close of systemUI right after boot, and it was smooth sailing right after.

**Comment by ArianK16a** [comment]
> > Updated this morning and it works great. Is it me, or are the haptics much improved?
> 
> Were you able to simply apply the update as an OTA or did you need to format your data partition?

The integrated updater does not offer major android upgrades due to possible addon incompabilities, so everyone should upgrade manually and ensure their addons are still fine (gapps usually need to be updated for example). You don't need to wipe data, you can just sideload it, as @rutgerputter said :)



> I had one force close of systemUI right after boot, and it was smooth sailing right after.

I've also noticed that, should be investigated! I'll create an issue about it for now since i don't really have time to dive in already.

**Comment by rutgerputter** [comment]
Just to bring my 2 cents when using Lineage 23 as my daily driver for a while now; I'm only missing 2 things that would bring this to feature parity to /e/ OS or Fairphone OS:

- 50MP camera option #23 (no biggie but nice to have when out and about)
- Being able to relock the bootloader #30
  - I'd love to load the public key of Lineage or any dev I trust and have builds signed with that key boot with a locked bootloader

**Comment by ArianK16a** [comment]
> Just to bring my 2 cents when using Lineage 23 as my daily driver for a while now; I'm only missing 2 things that would bring this to feature parity to /e/ OS or Fairphone OS:
> 
>     * 50MP camera option [Camera improvement #23](https://github.com/ArianK16a/android_device_fairphone_FP6/issues/23) (no biggie but nice to have when out and about)
> 
>     * Being able to relock the bootloader [Relocking the bootloader  #30](https://github.com/ArianK16a/android_device_fairphone_FP6/issues/30)
>       
>       * I'd love to load the public key of Lineage or any dev I trust and have builds signed with that key boot with a locked bootloader

Regarding the stock camera, i personally consider it an anti-feature since it's a proprietary app with system privileges (and also it does horrible post processing imo). If you want to get it working, you might need fairphones changes to libcameraservice: https://gerrit-public.fairphone.software/plugins/gitiles/platform/frameworks/av/+log/refs/heads/odm/rc/qssi/15/fp6/services/camera/libcameraservice

Lineage does not have keys used for verified boot, usually the AOSP test keys are used to sign the vbmeta images: https://github.com/ArianK16a/android_device_fairphone_FP6/blob/048bf5cf4617f19fd038de0be2b7684f2629f6a2/BoardConfig.mk#L220
I will probably make this configurable soon to allow overwriting this with custom keys and sign my builds correctly to be able to re-lock the bootloader.

**Comment by rutgerputter** [comment]
> Regarding the stock camera, i personally consider it an anti-feature since it's a proprietary app with system privileges (and also it does horrible post processing imo). If you want to get it working, you might need fairphones changes to libcameraservice: https://gerrit-public.fairphone.software/plugins/gitiles/platform/frameworks/av/+log/refs/heads/odm/rc/qssi/15/fp6/services/camera/libcameraservice
> 

I agree that the stock camera is an anti-feature, I prefer the lineage camera app. But I was hoping for a 50MP option in there. Oh well, I can live without it.

> 
> I will probably make this configurable soon to allow overwriting this with custom keys and sign my builds correctly to be able to re-lock the bootloader.

That would be awesome! I would greatly appreciate this.

**Comment by ArianK16a** [comment]
> > Regarding the stock camera, i personally consider it an anti-feature since it's a proprietary app with system privileges (and also it does horrible post processing imo). If you want to get it working, you might need fairphones changes to libcameraservice: https://gerrit-public.fairphone.software/plugins/gitiles/platform/frameworks/av/+log/refs/heads/odm/rc/qssi/15/fp6/services/camera/libcameraservice
> 
> I agree that the stock camera is an anti-feature, I prefer the lineage camera app. But I was hoping for a 50MP option in there. Oh well, I can live without it.
> 
Unfortunately 50MP won't be supported in Aperture, these high MP modes are usually not implemented using standard features.

**Comment by wunderbar78** [comment]
hey guys,
what is the state of the ROM being released as official version?

Cheers! ✌️

**Comment by mstaz** [comment]
Unfortunately git.mainlining.org is down at the moment. So I tried to extract the blobs myself, but the `extract-files.py` command fails for me. Which command did you use to do that?
As I don't have enough space in my tmpfs I used `--keep-dump` to extract it to subfolder:
```
> ./extract-files.py --keep-dump --extract-all ~/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory.zip                                                                                                                                                                                                                                       
Parsing device/fairphone/FP6/proprietary-firmware.txt
Parsing device/fairphone/FP6/proprietary-files.txt
Extracting to new dump dir /home/max/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory
Extracting file /home/max/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory.zip
Found sparse raw files: super.img
Deleting super.img_sparsechunk.0
Partition product not extracted
Partition system not extracted
Partition vendor not extracted
Partition system_ext not extracted
Backing up device/fairphone/FP6/proprietary-files.txt
Failed to back up system/framework/WfdCommon.jar
Failed to back up system_ext/bin/wfdservice64
...
Failed to back up system_ext/priv-app/WfdService/WfdService.apk
Processing device/fairphone/FP6/proprietary-firmware.txt
Processing device/fairphone/FP6/proprietary-files.txt
product/app/uimgbaservice/uimgbaservice.apk: file not found
product/app/uimlpaservice/uimlpaservice.apk: file not found
...
```
Edit:
Or also tried with e.g.
```
./extract-files.py --keep-dump --extract-all --download-dir ~/android/blobs https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP6/A15/FP6.QREL.15.122.0.20250718182448_VS1E-factory.zip
```

**Comment by ArianK16a** [comment]
> Unfortunately git.mainlining.org is down at the moment. So I tried to extract the blobs myself, but the `extract-files.py` command fails for me. Which command did you use to do that? As I don't have enough space in my tmpfs I used `--keep-dump` to extract it to subfolder:
> 
> ```
> > ./extract-files.py --keep-dump --extract-all ~/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory.zip                                                                                                                                                                                                                                       
> Parsing device/fairphone/FP6/proprietary-firmware.txt
> Parsing device/fairphone/FP6/proprietary-files.txt
> Extracting to new dump dir /home/max/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory
> Extracting file /home/max/android/blobs/FP6.QREL.15.151.0.20251011181017_VS1P-factory.zip
> Found sparse raw files: super.img
> Deleting super.img_sparsechunk.0
> Partition product not extracted
> Partition system not extracted
> Partition vendor not extracted
> Partition system_ext not extracted
> Backing up device/fairphone/FP6/proprietary-files.txt
> Failed to back up system/framework/WfdCommon.jar
> Failed to back up system_ext/bin/wfdservice64
> ...
> Failed to back up system_ext/priv-app/WfdService/WfdService.apk
> Processing device/fairphone/FP6/proprietary-firmware.txt
> Processing device/fairphone/FP6/proprietary-files.txt
> product/app/uimgbaservice/uimgbaservice.apk: file not found
> product/app/uimlpaservice/uimlpaservice.apk: file not found
> ...
> ```
> 
> Edit: Or also tried with e.g.
> 
> ```
> ./extract-files.py --keep-dump --extract-all --download-dir ~/android/blobs https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP6/A15/FP6.QREL.15.122.0.20250718182448_VS1E-factory.zip
> ```

You can use the command mentioned in the build instructions which are linked in the first post of this issue.

**Comment by mstaz** [comment]
Works now. Same commands that I tried yesterday. Maybe there was a temporary issue in the scripts or something. Or I did something wrong 😄 
Thanks for your hint. From the comment in the `proprietary-files.txt` it sounds like for 23.1 you used the 15.151 package, didn't you?

**Comment by ArianK16a** [comment]
> Works now. Same commands that I tried yesterday. Maybe there was a temporary issue in the scripts or something. Or I did something wrong 😄 
> Thanks for your hint. From the comment in the `proprietary-files.txt` it sounds like for 23.1 you used the 15.151 package, didn't you?

Yes that's right!
